import type { Manifest, Harness } from "../manifest/manifest.js";
import type { SourceResolver, Provenance } from "../sources/source.js";
import type { OutputPlan } from "../sync/plan.js";
export async function composeInstructions(
  manifest: Manifest,
  sources: SourceResolver,
  plan: OutputPlan,
) {
  if (!manifest.instructions.length) return;
  const fragments: {
    text: string;
    provenance: Provenance;
    targets?: Harness[];
  }[] = [];
  for (const spec of manifest.instructions) {
    const source = await sources.resolve(spec);
    fragments.push({
      text: (await source.file(spec.path)).content.toString("utf8").trim(),
      provenance: source.provenance(spec.path),
      targets: spec.targets,
    });
  }
  const forTarget = (target: Harness) =>
    fragments.filter((f) => !f.targets || f.targets.includes(target));
  const agents = forTarget("codex");
  const claude = forTarget("claude");
  const content = (sections: typeof fragments) =>
    `${sections.map((f) => f.text).join("\n\n<!-- agent-sync -->\n\n")}\n`;
  const shared = agents.length > 0 && content(agents) === content(claude);
  if (agents.length && (manifest.targets.some((t) => t !== "claude") || shared))
    plan.text(
      "AGENTS.md",
      content(agents),
      "instructions",
      agents.map((f) => f.provenance),
    );
  if (manifest.targets.includes("claude") && claude.length)
    plan.text(
      "CLAUDE.md",
      shared
        ? "<!-- Generated by agent-sync. Edit the declared instruction sources. -->\n@AGENTS.md\n"
        : content(claude),
      "instructions",
      claude.map((f) => f.provenance),
    );
}
